"use strict";

const countries = [
  { korean: "한국", english: "South Korea" },
  { korean: "미국", english: "United States" },
  { korean: "중국", english: "China" },
  { korean: "일본", english: "Japan" },
  { korean: "북한", english: "North Korea" },
  { korean: "인도", english: "India" },
  { korean: "인도네시아", english: "Indonesia" },
  { korean: "파키스탄", english: "Pakistan" },
  { korean: "브라질", english: "Brazil" },
  { korean: "나이지리아", english: "Nigeria" },
  { korean: "방글라데시", english: "Bangladesh" },
  { korean: "러시아", english: "Russia" },
  { korean: "멕시코", english: "Mexico" },
  { korean: "에티오피아", english: "Ethiopia" },
  { korean: "필리핀", english: "Philippines" },
  { korean: "이집트", english: "Egypt" },
  { korean: "베트남", english: "Vietnam" },
  { korean: "콩고민주공화국", english: "Democratic Republic of the Congo" },
  { korean: "터키", english: "Turkey" },
  { korean: "이란", english: "Iran" },
  { korean: "독일", english: "Germany" },
  { korean: "태국", english: "Thailand" },
  { korean: "영국", english: "United Kingdom" },
  { korean: "프랑스", english: "France" },
  { korean: "이탈리아", english: "Italy" },
  { korean: "남아프리카 공화국", english: "South Africa" },
  { korean: "탄자니아", english: "Tanzania" },
  { korean: "미얀마", english: "Myanmar" },
  { korean: "대한민국", english: "South Korea" },
  { korean: "콜롬비아", english: "Colombia" },
  { korean: "케냐", english: "Kenya" },
  { korean: "스페인", english: "Spain" },
  { korean: "우간다", english: "Uganda" },
  { korean: "아르헨티나", english: "Argentina" },
  { korean: "알제리", english: "Algeria" },
  { korean: "우크라이나", english: "Ukraine" },
  { korean: "수단", english: "Sudan" },
  { korean: "폴란드", english: "Poland" },
  { korean: "캐나다", english: "Canada" },
  { korean: "이라크", english: "Iraq" },
  { korean: "말레이시아", english: "Malaysia" },
  { korean: "우즈베키스탄", english: "Uzbekistan" },
  { korean: "모로코", english: "Morocco" },
  { korean: "아프가니스탄", english: "Afghanistan" },
  { korean: "사우디아라비아", english: "Saudi Arabia" },
  { korean: "우크라이나", english: "Ukraine" },
  { korean: "베네수엘라", english: "Venezuela" },
  { korean: "앙골라", english: "Angola" },
  { korean: "모잠비크", english: "Mozambique" },
  { korean: "카메룬", english: "Cameroon" },
  { korean: "가나", english: "Ghana" },
  { korean: "말라위", english: "Malawi" },
];

const foodItems = [
  { korean: "김치", english: "Kimchi" },
  { korean: "불고기", english: "Bulgogi" },
  { korean: "비빔밥", english: "Bibimbap" },
  { korean: "떡볶이", english: "Tteokbokki" },
  { korean: "삼겹살", english: "Samgyeopsal" },
  { korean: "된장찌개", english: "Doenjang jjigae" },
  { korean: "김밥", english: "Gimbap" },
  { korean: "순대", english: "Sundae" },
  { korean: "갈비탕", english: "Galbitang" },
  { korean: "순두부찌개", english: "Sundubu jjigae" },
  { korean: "팥빙수", english: "Patbingsu" },
  { korean: "전복죽", english: "Jebokjuk" },
  { korean: "감자탕", english: "Gamjatang" },
  { korean: "호두과자", english: "Hodu gwaja" },
  { korean: "오징어채볶음", english: "Ojingeo chae bokkeum" },
  { korean: "김치찌개", english: "Kimchi jjigae" },
  { korean: "스시", english: "Sushi" },
  { korean: "햄버거", english: "Hamburger" },
  { korean: "피자", english: "Pizza" },
  { korean: "카레", english: "Curry" },
  { korean: "나쵸", english: "Nachos" },
  { korean: "파스타", english: "Pasta" },
  { korean: "타코", english: "Taco" },
  { korean: "쌀국수", english: "Pho" },
  { korean: "양고기", english: "Lamb" },
  { korean: "우동", english: "Udon" },
  { korean: "삼각김밥", english: "Onigiri" },
  { korean: "참치회", english: "Tuna sashimi" },
  { korean: "푸팟퐁커리", english: "Pad Thai" },
  { korean: "스테이크", english: "Steak" },
  { korean: "크로와상", english: "Croissant" },
];
